models/Akun.php
<?php

namespace app\models;

use yii\db\ActiveRecord;

class Akun extends ActiveRecord
{
    public static function tableName()
    {
        return 'account';
    }
    public function rules()
    {
        return [
            ['username', 'required','message' => 'Username gak boleh kosong'],
            ['name', 'string','max'=>'20'],
            ['password', 'required','message' => 'Password gak boleh kosong'],
            ['role', 'string','max'=>'25'],
        ];
    }
}

models/AkunForm.php
<?php

namespace app\models;

use yii\base\Model;

class AkunForm extends Model
{
    public $username;
    public $name;
    public $password;
    public $role;

    public function attributeLabels()
    {
        return [
            'username' => 'Username',
            'name' => 'Name',
            'password' => 'Password',
            'role' => 'Role'
        ];
    }

    public function rules()
    {
        return [
            ['username', 'required','message' => 'Username gak boleh kosong'],
            ['name', 'string','max'=>'20'],
            ['password', 'required','message' => 'Password gak boleh kosong'],
            ['role', 'string','max'=>'25'],
        ];
    }
}

controllers/AkunController.php
<?php
namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\helpers\Url;

use app\models\Akun;
//use app\models\AkunForm;

class AkunController extends Controller{

    public function actions(){
        return ['error' => ['class' => 'yii\web\ErrorAction',],];
    }

     public function behaviors(){
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['index',],
                'rules' => [
                    [
                        'actions' => ['index',],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }


   public function actionIndex(){
        //if (Yii::$app->user->identity->username!='admin'){
          //  return $this->render('index');
       // }
    $query = Akun::find()->all();

        return $this->render('index', ['akuns'=>$query]);
    }

    public function actionAdd(){
        $akun = new Akun();
        if ($akun->load(Yii::$app->request->post())){
            $akun->password = md5($akun->password);
            $akun->save();

            return $this->redirect(Url::to(['akun/index']));
        }else{

            return $this->render('add', ['model'=>$akun]);

        }
    }

    public function actionDetail($id){
        $akun = Akun::findOne(['username'=>$id]);
        return $this->render('detail', ['akun'=>$akun]);
    }

    public function actionEdit($id){
        $akun = Akun::findOne($id);
        if ($akun->load(Yii::$app->request->post())){
            $akun->password = md5($akun->password);
            $akun->save();
           // echo "<pre>";print_r($akun);die();
            return $this->redirect(Url::to(['akun/detail', 'id'=>$id]));
        }else{

            return $this->render('edit', ['model'=>$akun, 'akun'=>$akun]);
        }
    }

    public function actionDelete($id){
        $akun = Akun::findOne(['username' => $id]);
        $akun->delete();

        return $this->redirect(Url::to(['akun/index']));
    }

    public function actionDeleteAll(){
        Akun::deleteAll();
        return $this->redirect(Url::to(['akun/index']));
    }
}

views/akun/add.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\widgets\Breadcrumbs;
use yii\helpers\Url;

$this->title = "Tambah";

?>

<div class="row">
    <div class="col-md-12">
        <h1>Tambah</h1>
        <hr/>
        <?php
        echo Breadcrumbs::widget([
            'itemTemplate' => "<li>{link}</li>\n", // template for all links
            'links' => [['label' => 'Akun', 'url' => ['akun/index']],'Tambah Akun',],]);
        ?>
    </div>
</div>

<div>   
    <div class="col-md-12">
        <?php $form = ActiveForm::begin([
                'id' => 'akuns-form',
                'options' => ['class' => 'form-horizontal']
            ])
        ?>

        <div class="form-group">
            <div class="col-lg-8">
            <?= $form->field($model, 'username')->hint('Harus Diisi'); ?>
            </div>
        </div>
        <div class="form-group">
            <div class="col-lg-8">
            <?= $form->field($model, 'name'); ?>
            </div>
        </div>
        <div class="form-group">
            <div class="col-lg-8">
            <?= $form->field($model, 'password')->passwordInput(); ?>
            </div>
        </div>
        <div class="form-group">
            <div class="col-lg-8">
            <?= $form->field($model, 'role'); ?>
            </div>
        </div>
        <div class="form-group">
            <div class="col-lg-8">
                <?= Html::submitButton('Simpan', ['class' => 'btn btn-primary']) ?>
            </div>
        </div>

        <?php ActiveForm::end(); ?>
    </div>
</div>

views/akun/detail.php
<?php

use yii\widgets\Breadcrumbs;
use yii\helpers\Url;

$this->title = "Detail";

?>

<div class="row">
    <div class="col-md-12">
        <h1><?php echo $akun['name'] ?></h1>
        <hr/>
        <?php
        echo Breadcrumbs::widget([
            'itemTemplate' => "<li>{link}</li>\n", // template for all links
            'links' => [['label' => 'Akun', 'url' => ['akun/index']],'Detail Akun',],]);
        ?>
    </div>
</div>

<div>   
    <div class="col-md-2">
        <div class="list-group">
          <a href="<?php echo Url::to(['akun/edit', 'id'=>$akun['username']]); ?>" class="list-group-item"><i class="glyphicon glyphicon-pencil"></i> Edit Akun</a>
          <a href="<?php echo Url::to(['akun/delete', 'id'=>$akun['username']]); ?>" class="list-group-item"><i class="glyphicon glyphicon-trash"></i> Delete Akun</a>
        </div>
    </div>
    <div class="col-md-10">

        <div class="col-md-8">
        	<table>
        		<tr>
        			<th>Username</th>
        			<td>:</td>
        			<td><?php echo $akun['username'] ?></td>
        		</tr>
        		<tr>
        			<th>Name</th>
        			<td>:</td>
        			<td><?php echo $akun['name'] ?></td>
        		</tr>
        		<tr>
        			<th>Role</th>
        			<td>:</td>
        			<td><?php echo $akun['role'] ?></td>
        		</tr>
                <tr>
                    <th>password</th>
                    <td>:</td>
                    <td><?php echo $akun['password'] ?></td>
                </tr>
        	</table>
        </div>
</div>

views/akun/edit.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\widgets\Breadcrumbs;
use yii\helpers\Url;

$this->title = "Edit";

?>

<div class="row">
    <div class="col-md-12">
        <h1>Edit <?php echo $model['name'] ?></h1>
        <hr/>
        <?php

        echo Breadcrumbs::widget([
            'itemTemplate' => "<li>{link}</li>\n", // template for all links
            'links' => [
                ['label' => 'Akun', 'url' => ['akun/index']],
                'Edit '.$model['name'],
            ],
        ]);

        ?>
    </div>
</div>

<div>   
    <div class="col-md-12">
        <?php $form = ActiveForm::begin([
                'id' => 'akun-form',
                'options' => ['class' => 'form-horizontal']
            ])
        ?>

        <div class="form-group">
            <div class="col-lg-8">
            <?= $form->field($model, 'username')->textInput(); ?>
            </div>
        </div>
        <div class="form-group">
            <div class="col-lg-8">
            <?= $form->field($model, 'name')->textInput()->hint(' huruf besar'); ?>
            </div>
        </div>
        <div class="form-group">
            <div class="col-lg-8">
            <?= $form->field($model, 'password')->input('password'); ?>
            </div>
        </div>
        <div class="form-group">
            <div class="col-lg-8">
            <?= $form->field($model, 'role')->TextArea(); ?>
            </div>
        </div>
        <div class="form-group">
            <div class="col-lg-8">
                <?= Html::submitButton('Simpan', ['class' => 'btn btn-primary']) ?>
            </div>
        </div>

        <?php ActiveForm::end(); ?>
    </div>
</div>

views/akun/index.php
<?php

use yii\helpers\Html;
use yii\widgets\Breadcrumbs;
use yii\helpers\Url;

$this->title = "CRUD";

?>

<div class="row">
    <div class="col-md-12">
        <?php

        echo Breadcrumbs::widget([
            'itemTemplate' => "<li>{link}</li>\n", // template for all links
            'links' => [
                'Akun List',
            ],
        ]);

        ?>
        <hr/>
        <h1>Akun</h1>
        <a href="<?php echo Url::to(['akun/add']); ?>"><button><i class="glyphicon glyphicon-plus"></i>Tambah</button></a>
    </div>
</div>

<div>   
    <div class="col-md-12">
        <table class="table table-striped">
            <thead>
              <tr>
                <th>#</th>
                <th>Username</th>
                <th>Name</th>
                <th>Role</th>
                <th></th>
              </tr>
            </thead>
            <tbody>
                <?php 
                if (count($akuns) > 0) { ?>
                    <?php 
                    $no =1;
                    foreach ($akuns as $akun): ?>
                        <tr>
                            <td><?= $no ?></td>
                            <td><?= Html::encode("{$akun['username']}") ?></td>
                            <td><?= Html::encode("{$akun['name']}") ?></td>
                            <td><?= Html::encode("{$akun['role']}") ?></td>
                            <td style="width:15%;text-align:center;">
                                <a href="<?php echo Url::to(['akun/delete', 'id'=>$akun['username']]); ?>"><i class="glyphicon glyphicon-trash"></i></a>
                                <a href="<?php echo Url::to(['akun/detail', 'id'=>$akun['username']]); ?>"><i class="glyphicon glyphicon-eye-open"></i></a>
                                <a href="<?php echo Url::to(['akun/edit', 'id'=>$akun['username']]); ?>"><i class="glyphicon glyphicon-pencil"></i></a> 
                            </td>
                          </tr>
                    <?php 
                    $no++;
                endforeach; ?>
                <?php 
                } else { ?>
                <tr>
                    <td style="text-align:center;font-size:15px;padding:25px;" colspan="5">No data found...</td>
                </tr>
                <?php } ?>

            </tbody>
          </table>
    </div>
</div>