models/Post.php
<?php

namespace app\models;

use yii\db\ActiveRecord;

class Post extends ActiveRecord
{
    public static function tableName()
    {
        return 'post';
    }
    public function rules()
    {
        return [
            ['title', 'required','message' => 'gak boleh kosong'],
            ['content', 'required','message' => 'gak boleh kosong'],];
    }
    public function getKomen(){
        return $this->hasMany(Komen::className(), ['idpost' => 'idpost']);
    }

    
}

models/PostForm.php
<?php

namespace app\models;

use yii\base\Model;

class PostForm extends Model
{
    public $title;
    public $content;

    public function attributeLabels()
    {
        return [
            'title' => 'Title',
            'content' => 'Content'];
    }

    public function rules()
    {
        return [
            ['title', 'required','message' => 'gak boleh kosong'],
            ['content', 'required','message' => 'gak boleh kosong'],];
    }
}

controllers/PostController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\helpers\Url;

use app\models\Post;
//use app\models\PostForm;

class PostController extends Controller{

    public function actions(){
        return ['error' => ['class' => 'yii\web\ErrorAction',],];
    }

     public function behaviors(){
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['index',],
                'rules' => [
                    [
                        'actions' => ['index',],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }


   public function actionIndex(){
	$query = Post::find();
    $post = $query->orderBy('idpost')->all();

        return $this->render('index', ['post'=>$post]);
    }

    public function actionAdd(){
        $post = new Post();
        if ($post->load(Yii::$app->request->post())){
            $post->date = date("Y-m-d H:i:s");
            $post->username = Yii::$app->user->identity->username;
            $post->save();

            return $this->redirect(Url::to(['post/index']));
        }else{
            //$akun = Akun::find()->select(['name', 'username'])->indexBy('username')->column();

            return $this->render('add', ['model'=>$post]);

        }
    }

    public function actionDetail($id){
        $post = Post::findOne(['idpost'=>$id]);
        return $this->render('detail', ['post'=>$post]);
    }

    public function actionEdit($id){
       $post = Post::findOne($id);
       if ($post->load(Yii::$app->request->post())){
            $post->date = date("Y-m-d H:i:s");
            $post->username = 'admin';
            $post->save();
            //echo "<pre>";print_r($post);die();
            return $this->redirect(Url::to(['post/detail', 'id'=>$id]));
            }else{

            return $this->render('edit', ['model'=>$post]);
            }
    }

    public function actionDelete($id){
        $post = Post::findOne(['idpost' => $id]);
        $post->delete();

        return $this->redirect(Url::to(['post/index']));
    }

    public function actionDeleteAll(){
        Akun::deleteAll();
        return $this->redirect(Url::to(['post/index']));
    }


    }

views/post/add.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\widgets\Breadcrumbs;
use yii\widgets\DatePicker;
use yii\helpers\Url;
use dosamigos\tinymce\TinyMce;

$this->title = "Tambah";

?>
<div class="row">
    <div class="col-md-12">
        <h1>Tambah</h1>
        <hr/>
        <?php
        echo Breadcrumbs::widget([
            'itemTemplate' => "<li>{link}</li>\n", // template for all links
            'links' => [['label' => 'Post', 'url' => ['post/index']],'Tambah Post',],]);
        ?>
    </div>
</div>

<div>   
    <div class="col-md-12">
        <?php $form = ActiveForm::begin([
                'id' => 'post-form',
                'options' => ['class' => 'form-horizontal']
            ])
        ?>

        <div class="form-group">
            <div class="col-lg-8">
            <?= $form->field($model, 'title')->hint('Harus Diisi'); ?>
            </div>
        </div>
        <!--<div class="form-group">
            <div class="col-lg-8">
            <?= $form->field($model, 'content')->textarea(); ?>
            </div>
        </div>-->
        <div>
            <?= $form->field($model, 'content')->widget(TinyMce::className(), [
            'options' => ['rows' => 6],
            'language' => 'es',
            'clientOptions' => [
                'plugins' => [
                    "advlist autolink lists link charmap print preview anchor",
                    "searchreplace visualblocks code fullscreen",
                    "insertdatetime media table contextmenu paste"
                ],
            'toolbar' => "undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image"
                ]
            ]);?>
        </div>
        <div class="form-group">
            <div class="col-lg-8">
                <?= Html::submitButton('Simpan', ['class' => 'btn btn-primary']) ?>
                <?= Html::Button('Back', ['onclick' => "history.go(-1)", 'class' => 'btn btn-danger']) ?>
            </div>
        </div>

        <?php ActiveForm::end(); ?>
    </div>
</div>

views/post/detail.php
<?php

use yii\widgets\Breadcrumbs;
use yii\helpers\Url;

$this->title = "Detail";

?>

<div class="row">
    <div class="col-md-12">
        <h1><?php echo $post['title'] ?></h1>
        <hr/>
        <?php
        echo Breadcrumbs::widget([
            'itemTemplate' => "<li>{link}</li>\n", // template for all links
            'links' => [['label' => 'post', 'url' => ['post/index']],'Detail Akun',],]);
        ?>
    </div>
</div>

<div>   
    <div class="col-md-2">
        <div class="list-group">
          <a href="<?php echo Url::to(['post/edit', 'id'=>$post['idpost']]); ?>" class="list-group-item"><i class="glyphicon glyphicon-pencil"></i> Edit Post</a>
          <a href="<?php echo Url::to(['post/delete', 'id'=>$post['idpost']]); ?>" class="list-group-item"><i class="glyphicon glyphicon-trash"></i> Delete Post</a>
        </div>
    </div>
    <div class="col-md-10">

        <div class="col-md-8">
        	<table>
        		<tr>
        			<th>Title</th>
        			<td>:</td>
        			<td><?php echo $post['title'] ?></td>
        		</tr>
        		<tr>
        			<th>Name</th>
        			<td>:</td>
        			<td><?php echo $post['content'] ?></td>
        		</tr>
        		<tr>
        			<th>Date</th>
        			<td>:</td>
        			<td><?php echo $post['date'] ?></td>
        		</tr>
        		<tr>
        			<th>Username</th>
        			<td>:</td>
        			<td><?php echo $post['username'] ?></td>
        		</tr>
        	</table>
        </div>
</div>

views/post/edit.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\widgets\Breadcrumbs;
use yii\helpers\Url;
use dosamigos\tinymce\TinyMce;

$this->title = "Edit";
?>

<div class="row">
    <div class="col-md-12">
        <h1>Edit <?php echo $model['title'] ?></h1>
        <hr/>
        <?php

        echo Breadcrumbs::widget([
            'itemTemplate' => "<li>{link}</li>\n", // template for all links
            'links' => [
                ['label' => 'Post', 'url' => ['post/index']],
                'Edit '.$model['title'],
            ],
        ]);

        ?>
    </div>
</div>

<div>   
    <div class="col-md-12">
        <?php $form = ActiveForm::begin([
                'id' => 'post-form',
                'options' => ['class' => 'form-horizontal']
            ])
        ?>

        <div class="form-group">
            <div class="col-lg-8">
            <?= $form->field($model, 'title')->textInput(); ?>
            </div>
        </div>
        <div class="form-group">
            <div class="col-lg-8">
            <?= $form->field($model, 'content')->widget(TinyMce::className(), [
            'options' => ['rows' => 6],
            'language' => 'es',
            'clientOptions' => [
                'plugins' => [
                    "advlist autolink lists link charmap print preview anchor",
                    "searchreplace visualblocks code fullscreen",
                    "insertdatetime media table contextmenu paste"
                ],
            'toolbar' => "undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image"
                ]
        ]);?>
            </div
        </div>
        <div class="form-group">
            <div class="col-lg-8">
                <?= Html::submitButton('Simpan', ['class' => 'btn btn-primary']) ?>
            </div>
        </div>

        <?php ActiveForm::end(); ?>
    </div>
</div>

views/post/index.php
<?php

use yii\helpers\Html;
use yii\widgets\Breadcrumbs;
use yii\helpers\Url;

$this->title = "CRUD";

?>

<div class="row">
    <div class="col-md-12">
        
        <?php

        echo Breadcrumbs::widget([
            'itemTemplate' => "<li>{link}</li>\n", // template for all links
            'links' => [
                'Post',
            ],
        ]);

        ?>
        <hr/>
        <h1>Post</h1>
        <a href="<?php echo Url::to(['post/add']); ?>"><button><i class="glyphicon glyphicon-plus"></i>Tambah</button></a>
    </div>
</div>

<div>   
    <div class="col-md-12">
        <table class="table table-striped">
            <thead>
              <tr>
                <th>#</th>
                <th>Judul</th>
                <th>ISI</th>
                <th>Date</th>
                <th>Username</th>
                <th></th>
              </tr>
            </thead>
            <tbody>
                <?php 
                $no =1;
                if (count($post) > 0) { ?>
                    <?php foreach ($post as $post): ?>
                        <tr>
                            <td><?= $no ?></td>
                            <td><?= Html::encode("{$post['title']}") ?></td>
                            <td><?=("{$post['content']}") ?></td>
                            <td><?= Html::encode("{$post['date']}") ?></td>
                            <td><?= Html::encode("{$post['username']}") ?></td>
                            <td style="width:15%;text-align:center;">
                                <a href="<?php echo Url::to(['post/delete', 'id'=>$post['idpost']]); ?>"><i class="glyphicon glyphicon-trash"></i></a>
                                <a href="<?php echo Url::to(['post/detail', 'id'=>$post['idpost']]); ?>"><i class="glyphicon glyphicon-eye-open"></i></a>
                                <a href="<?php echo Url::to(['post/edit', 'id'=>$post['idpost']]); ?>"><i class="glyphicon glyphicon-pencil"></i></a> 
                            </td>
                          </tr>
                    <?php 
                     $no++;
                endforeach; ?>
                <?php } else { ?>
                <tr>
                    <td style="text-align:center;font-size:15px;padding:25px;" colspan="5">No data found...</td>
                </tr>
                <?php 
                $no++;
            } ?>

            </tbody>
          </table>
    </div>
</div>